//
//  TravelModelStore.swift
//  TravelMaker
//
//  Created by 이우석 on 2/20/24.
//

import Foundation

class TravelModelStore {
    var travelStore: [TravelModel]
    
    let users = UserModelStore()
    
    init() {
        travelStore = [
            TravelModel(title: "가가가 전역 식물원 탐방", imageName: "food1", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .food),
            TravelModel(title: "제주도 전역 식물원 탐방", imageName: "food2", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .food),
            TravelModel(title: "제주도 전역 식물원 탐방", imageName: "yeomiji", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .food),
            TravelModel(title: "나나나 전역 식물원 탐방", imageName: "art1", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .art),
            TravelModel(title: "제주도 전역 식물원 탐방", imageName: "art2", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .art),
            TravelModel(title: "제주도 전역 식물원 탐방", imageName: "art3", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .art),
            TravelModel(title: "다다다 전역 식물원 탐방", imageName: "leasure1", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .leasure),
            TravelModel(title: "제주도 전역 식물원 탐방", imageName: "leasure2", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .leasure),
            TravelModel(title: "제주도 전역 식물원 탐방", imageName: "leasure3", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .leasure),
            TravelModel(title: "라라라 전역 식물원 탐방", imageName: "yeomiji", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .photo),
            TravelModel(title: "제주도 전역 식물원 탐방", imageName: "yeomiji", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .photo),
            TravelModel(title: "제주도 전역 식물원 탐방", imageName: "yeomiji", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .photo),
            TravelModel(title: "마마마 전역 식물원 탐방", imageName: "culture1", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .culture),
            TravelModel(title: "제주도 전역 식물원 탐방", imageName: "culture2", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .culture),
            TravelModel(title: "제주도 전역 식물원 탐방", imageName: "culture3", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .culture),
            TravelModel(title: "바바바 전역 식물원 탐방", imageName: "nature1", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .nature),
            TravelModel(title: "제주도 전역 식물원 탐방", imageName: "nature2", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .nature),
            TravelModel(title: "제주도 전역 식물원 탐방", imageName: "nature3", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .nature),
        ]
    }
}
