//
//  TravelModelStore.swift
//  TravelMaker
//
//  Created by 이우석 on 2/20/24.
//

import Foundation

class TravelModelStore {
    var travelStore: [TravelModel]
    
    let users = UserModelStore()
    
    init() {
        travelStore = [
            TravelModel(title: "제주도 맛집탐방", imageName: "food1", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .food),
            TravelModel(title: "제주도 맛집탐방", imageName: "food2", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .food),
            TravelModel(title: "제주도 전역 식물원 탐방", imageName: "yeomiji", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .food),
            TravelModel(title: "제주도 박물관, 미술관 탐방", imageName: "art1", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .art),
            TravelModel(title: "제주도 박물관, 미술관 탐방", imageName: "art2", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .art),
            TravelModel(title: "제주도 박물관, 미술관 탐방", imageName: "art3", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .art),
            TravelModel(title: "제주도 보트 투어", imageName: "leasure1", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .leasure),
            TravelModel(title: "하늘 높이! 한라산 열기구 투어", imageName: "leasure2", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .leasure),
            TravelModel(title: "즐거운 ATV 투어", imageName: "leasure3", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .leasure),
            TravelModel(title: "서귀포시 포토스팟 모두 보기", imageName: "yeomiji", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .photo),
            TravelModel(title: "서귀포시 포토스팟 모두 보기", imageName: "yeomiji", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .photo),
            TravelModel(title: "서귀포시 포토스팟 모두 보기", imageName: "yeomiji", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .photo),
            TravelModel(title: "제주도 정원탐방하기", imageName: "culture1", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .culture),
            TravelModel(title: "돌하르방 자세히 알아보기", imageName: "culture2", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .culture),
            TravelModel(title: "제주도 정원탐방하기", imageName: "culture3", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .culture),
            TravelModel(title: "제주도 해변 힐링", imageName: "nature1", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .nature),
            TravelModel(title: "배 타고 나가서 구경하는 이색적인 풍경", imageName: "nature2", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .nature),
            TravelModel(title: "오름 등반하기", imageName: "nature3", author: users.userStore.first!, guideProfileImage: "subway", price: 50000, location: "제주특별자치도", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.", tag: .nature),
        ]
    }
}
